export const FALLBACK_MANDI_ROWS = [
  {
    crop: 'Wheat',
    market: 'Kolar APMC',
    district: 'Kolar',
    state: 'Karnataka',
    minPrice: 2200,
    maxPrice: 2580,
    modalPrice: 2450,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Rice',
    market: 'Mysuru Market Yard',
    district: 'Mysuru',
    state: 'Karnataka',
    minPrice: 2600,
    maxPrice: 3120,
    modalPrice: 2980,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Ragi',
    market: 'Bengaluru APMC',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    minPrice: 2900,
    maxPrice: 3400,
    modalPrice: 3225,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Cotton',
    market: 'Adilabad Mandi',
    district: 'Adilabad',
    state: 'Telangana',
    minPrice: 6600,
    maxPrice: 7600,
    modalPrice: 7200,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Maize',
    market: 'Warangal Yard',
    district: 'Warangal',
    state: 'Telangana',
    minPrice: 1950,
    maxPrice: 2450,
    modalPrice: 2280,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Paddy',
    market: 'Guntur Yard',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    minPrice: 2150,
    maxPrice: 2680,
    modalPrice: 2490,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Groundnut',
    market: 'Anantapur Mandi',
    district: 'Anantapur',
    state: 'Andhra Pradesh',
    minPrice: 4800,
    maxPrice: 6100,
    modalPrice: 5750,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Tur',
    market: 'Nagpur APMC',
    district: 'Nagpur',
    state: 'Maharashtra',
    minPrice: 6400,
    maxPrice: 7450,
    modalPrice: 6980,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Soybean',
    market: 'Latur APMC',
    district: 'Latur',
    state: 'Maharashtra',
    minPrice: 3900,
    maxPrice: 4720,
    modalPrice: 4380,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Sugarcane',
    market: 'Kolhapur Yard',
    district: 'Kolhapur',
    state: 'Maharashtra',
    minPrice: 290,
    maxPrice: 360,
    modalPrice: 330,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Potato',
    market: 'Agra Mandi',
    district: 'Agra',
    state: 'Uttar Pradesh',
    minPrice: 1300,
    maxPrice: 1900,
    modalPrice: 1680,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Mustard',
    market: 'Jaipur Mandi',
    district: 'Jaipur',
    state: 'Rajasthan',
    minPrice: 5100,
    maxPrice: 6200,
    modalPrice: 5900,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Bajra',
    market: 'Sikar Yard',
    district: 'Sikar',
    state: 'Rajasthan',
    minPrice: 2100,
    maxPrice: 2650,
    modalPrice: 2440,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Jute',
    market: 'Howrah Mandi',
    district: 'Howrah',
    state: 'West Bengal',
    minPrice: 3800,
    maxPrice: 4500,
    modalPrice: 4210,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
  {
    crop: 'Tea Leaf',
    market: 'Siliguri Yard',
    district: 'Darjeeling',
    state: 'West Bengal',
    minPrice: 12500,
    maxPrice: 16200,
    modalPrice: 14900,
    unit: 'INR/qtl',
    arrivalDate: '2026-04-03',
  },
];

